
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Retrospective
{

using System;
    using System.Collections.Generic;
    
public partial class V_ActionPlans
{

    public int sprintId { get; set; }

    public string sprintName { get; set; }

    public long sprintCommentId { get; set; }

    public string sprintComment { get; set; }

    public string Decisions { get; set; }

}

}
